# Generated by Django 6.0.5 on 2026-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logements', '0002_recherchehistorique'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='heure_visite',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_rencontre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
