# Generated by Django 6.0.5 on 2026-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiement_code_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='code_confirmation',
        ),
        migrations.AddField(
            model_name='paiement',
            name='campay_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='plan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='ussd_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
