# Generated by Django 6.0.5 on 2026-10-03 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20)),
                ('uid', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_sociaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte social',
                'verbose_name_plural': 'Comptes sociaux',
                'unique_together': {('fournisseur', 'uid')},
            },
        ),
    ]
